# Generated by Django 4.2.1 on 2023-09-20 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=255)),
                ("Description", models.TextField(blank=True, null=True)),
                (
                    "brand",
                    models.CharField(
                        choices=[
                            ("NIKE", "NIKE"),
                            ("HUBLOT", "HUBLOT"),
                            ("G-SHOK", "G-SHOK"),
                            ("ROLEX", "ROLEX"),
                            ("ADDIDAS", "ADDIDAS"),
                        ],
                        default="NIKE",
                        max_length=20,
                    ),
                ),
                ("Category_Quantity", models.IntegerField()),
                ("Stock_availble", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("P_Name", models.CharField(max_length=100)),
                (
                    "Size",
                    models.CharField(
                        choices=[
                            ("small", "small"),
                            ("medium", "medium"),
                            ("large", "large"),
                            ("x-large", "x-large"),
                        ],
                        default="small",
                        max_length=30,
                    ),
                ),
                (
                    "Colour",
                    models.CharField(
                        choices=[("black", "black"), ("white", "white")],
                        default="black",
                        max_length=30,
                    ),
                ),
                ("Price", models.PositiveIntegerField()),
                ("Rating", models.PositiveIntegerField()),
                ("Add_To_favourite", models.BooleanField(default=True)),
                (
                    "Product_Type",
                    models.CharField(
                        choices=[
                            ("Electronics", "Electronics"),
                            ("Clothing", "Clothing"),
                            ("watch", "watch"),
                        ],
                        default="Electronics",
                        max_length=20,
                    ),
                ),
                ("Description", models.TextField()),
                (
                    "Category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="watch.category"
                    ),
                ),
            ],
        ),
    ]
